/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author colli
 */
public class Formal extends javax.swing.JFrame {

    /**
     * Creates new form Formal
     */
    public Formal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleTextbox = new javax.swing.JTextField();
        assignmentTextbox = new javax.swing.JTextField();
        courseNameTextbox = new javax.swing.JTextField();
        titleLabel = new javax.swing.JLabel();
        formalTagPannel = new javax.swing.JPanel();
        formalDepartmentTemplateTextbox = new javax.swing.JTextField();
        formalTemplateTextbox = new javax.swing.JTextField();
        assignmentLabel = new javax.swing.JLabel();
        courseNumberTextbox = new javax.swing.JTextField();
        courseNumberCodeLabel = new javax.swing.JLabel();
        courseNameLabel = new javax.swing.JLabel();
        schoolTextbox = new javax.swing.JTextField();
        schoolLabel = new javax.swing.JLabel();
        authorCombo = new javax.swing.JComboBox<>();
        authorLabel = new javax.swing.JLabel();
        labTeamMemberCombo = new javax.swing.JComboBox<>();
        labTeamMemberLabel = new javax.swing.JLabel();
        authorEditButton = new javax.swing.JButton();
        labTeamMemberEditButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        headingsList = new javax.swing.JList<>();
        sectionsLabel = new javax.swing.JLabel();
        headingsLabel = new javax.swing.JLabel();
        sectionsEditButton = new javax.swing.JButton();
        month1Combo = new javax.swing.JComboBox<>();
        day1Combo = new javax.swing.JComboBox<>();
        year1Combo = new javax.swing.JComboBox<>();
        experimentPerfomredOnLabel = new javax.swing.JLabel();
        month2combo = new javax.swing.JComboBox<>();
        day2combo = new javax.swing.JComboBox<>();
        year2Combo = new javax.swing.JComboBox<>();
        submissionDateLabel = new javax.swing.JLabel();
        RTFCheckBox = new javax.swing.JCheckBox();
        latexCheckBox = new javax.swing.JCheckBox();
        generateButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Template Generator");
        setResizable(false);
        setSize(new java.awt.Dimension(700, 0));

        titleTextbox.setPreferredSize(new java.awt.Dimension(250, 20));

        assignmentTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignmentTextboxActionPerformed(evt);
            }
        });

        courseNameTextbox.setPreferredSize(new java.awt.Dimension(250, 20));
        courseNameTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseNameTextboxActionPerformed(evt);
            }
        });

        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleLabel.setText("Title:");
        titleLabel.setPreferredSize(new java.awt.Dimension(250, 14));

        formalTagPannel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        formalTagPannel.setPreferredSize(new java.awt.Dimension(270, 70));

        formalDepartmentTemplateTextbox.setEditable(false);
        formalDepartmentTemplateTextbox.setText("Electrical Engineering ");
        formalDepartmentTemplateTextbox.setPreferredSize(new java.awt.Dimension(250, 20));
        formalDepartmentTemplateTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formalDepartmentTemplateTextboxActionPerformed(evt);
            }
        });

        formalTemplateTextbox.setEditable(false);
        formalTemplateTextbox.setText("Formal");

        javax.swing.GroupLayout formalTagPannelLayout = new javax.swing.GroupLayout(formalTagPannel);
        formalTagPannel.setLayout(formalTagPannelLayout);
        formalTagPannelLayout.setHorizontalGroup(
            formalTagPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formalTagPannelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(formalTagPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formalDepartmentTemplateTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formalTemplateTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        formalTagPannelLayout.setVerticalGroup(
            formalTagPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formalTagPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formalDepartmentTemplateTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formalTemplateTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        assignmentLabel.setText("Assignment:");
        assignmentLabel.setPreferredSize(new java.awt.Dimension(250, 14));

        courseNumberCodeLabel.setText("Course Number Code:");
        courseNumberCodeLabel.setPreferredSize(new java.awt.Dimension(250, 14));

        courseNameLabel.setText("Course Name:");
        courseNameLabel.setPreferredSize(new java.awt.Dimension(250, 14));

        schoolTextbox.setPreferredSize(new java.awt.Dimension(250, 20));
        schoolTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolTextboxActionPerformed(evt);
            }
        });

        schoolLabel.setText("School:");
        schoolLabel.setPreferredSize(new java.awt.Dimension(250, 14));

        authorCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        authorLabel.setText("Author(s):");

        labTeamMemberLabel.setText("Lab Team Members:");

        authorEditButton.setLabel("Edit");

        labTeamMemberEditButton.setLabel("Edit");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        headingsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Abstract", "Introduction", "Theory ", "Methods", "      Experimental Procedure", "      Experimental Appratus", "      Material List", "Results ", "Disscussion", "Conclusion", "References ", "Apendix" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(headingsList);

        sectionsLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sectionsLabel.setText("Sections");

        headingsLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        headingsLabel.setText("Headings");

        sectionsEditButton.setText("Edit");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sectionsEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(sectionsLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(headingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sectionsEditButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(sectionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(headingsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );

        month1Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January ", "Febuary ", "March ", "April ", "May ", "June ", "July ", "August ", "September ", "October", "November", "December" }));

        day1Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        day1Combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day1ComboActionPerformed(evt);
            }
        });

        year1Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040" }));
        year1Combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year1ComboActionPerformed(evt);
            }
        });

        experimentPerfomredOnLabel.setText("Experiment Performed on:");

        month2combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January ", "Febuary ", "March ", "April ", "May ", "June ", "July ", "August ", "September ", "October", "November", "December" }));

        day2combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        day2combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day2comboActionPerformed(evt);
            }
        });

        year2Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040" }));

        submissionDateLabel.setText("Submission Date:");

        RTFCheckBox.setText("RTF");
        RTFCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RTFCheckBoxActionPerformed(evt);
            }
        });

        latexCheckBox.setText("LaTeX");
        latexCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latexCheckBoxActionPerformed(evt);
            }
        });

        generateButton.setText("Generate ");
        generateButton.setPreferredSize(new java.awt.Dimension(80, 20));
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        previousButton.setText("Previous");
        previousButton.setPreferredSize(new java.awt.Dimension(80, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(assignmentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(titleTextbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(courseNumberTextbox)
                            .addComponent(assignmentTextbox)
                            .addComponent(courseNumberCodeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(courseNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(courseNameTextbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(schoolTextbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(schoolLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(authorCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(authorLabel)
                            .addComponent(labTeamMemberCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labTeamMemberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(formalTagPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(authorEditButton)
                            .addComponent(labTeamMemberEditButton)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(experimentPerfomredOnLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(month1Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(day1Combo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(month2combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(day2combo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(submissionDateLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(year2Combo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(year1Combo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(RTFCheckBox)
                        .addGap(18, 18, 18)
                        .addComponent(latexCheckBox)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(previousButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(generateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(formalTagPannel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(titleTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(assignmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(assignmentTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(courseNumberCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(courseNumberTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(courseNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(courseNameTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(experimentPerfomredOnLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(schoolLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(month1Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(day1Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(year1Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(schoolTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(submissionDateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authorLabel)
                    .addComponent(month2combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day2combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year2Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(authorEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTeamMemberLabel)
                    .addComponent(RTFCheckBox)
                    .addComponent(latexCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTeamMemberCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labTeamMemberEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(previousButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formalDepartmentTemplateTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formalDepartmentTemplateTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formalDepartmentTemplateTextboxActionPerformed

    private void assignmentTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignmentTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assignmentTextboxActionPerformed

    private void courseNameTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseNameTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseNameTextboxActionPerformed

    private void schoolTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schoolTextboxActionPerformed

    private void day1ComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day1ComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_day1ComboActionPerformed

    private void day2comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day2comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_day2comboActionPerformed

    private void RTFCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RTFCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RTFCheckBoxActionPerformed

    private void latexCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latexCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_latexCheckBoxActionPerformed

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generateButtonActionPerformed

    private void year1ComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year1ComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_year1ComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox RTFCheckBox;
    private javax.swing.JLabel assignmentLabel;
    private javax.swing.JTextField assignmentTextbox;
    private javax.swing.JComboBox<String> authorCombo;
    private javax.swing.JButton authorEditButton;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JLabel courseNameLabel;
    private javax.swing.JTextField courseNameTextbox;
    private javax.swing.JLabel courseNumberCodeLabel;
    private javax.swing.JTextField courseNumberTextbox;
    private javax.swing.JComboBox<String> day1Combo;
    private javax.swing.JComboBox<String> day2combo;
    private javax.swing.JLabel experimentPerfomredOnLabel;
    private javax.swing.JTextField formalDepartmentTemplateTextbox;
    private javax.swing.JPanel formalTagPannel;
    private javax.swing.JTextField formalTemplateTextbox;
    private javax.swing.JButton generateButton;
    private javax.swing.JLabel headingsLabel;
    private javax.swing.JList<String> headingsList;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> labTeamMemberCombo;
    private javax.swing.JButton labTeamMemberEditButton;
    private javax.swing.JLabel labTeamMemberLabel;
    private javax.swing.JCheckBox latexCheckBox;
    private javax.swing.JComboBox<String> month1Combo;
    private javax.swing.JComboBox<String> month2combo;
    private javax.swing.JButton previousButton;
    private javax.swing.JLabel schoolLabel;
    private javax.swing.JTextField schoolTextbox;
    private javax.swing.JButton sectionsEditButton;
    private javax.swing.JLabel sectionsLabel;
    private javax.swing.JLabel submissionDateLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleTextbox;
    private javax.swing.JComboBox<String> year1Combo;
    private javax.swing.JComboBox<String> year2Combo;
    // End of variables declaration//GEN-END:variables
}
