
import java.io.File;
import java.io.IOException;
import java.nio.file.FileAlreadyExistsException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author colli
 */
public class Formal extends javax.swing.JFrame {
    
    private TEMPLATE template;
    private FORMAT   format;
    private String   department;
    private Headings h;
    private ArrayList<String> authors;
    private ArrayList<String> members;
    private ScriptEditor      script;

    /**
     * Creates new form Formal
     */
    public Formal() {
        initComponents();
    }
    
    public Formal(String department, TEMPLATE template) {
        this.template = template;
        this.department = department;

        authors = new ArrayList<>();
        members = new ArrayList<>();
        
        h = new Headings(TEMPLATE.FORMAL); // create the default heading tree
        
        initComponents(); 
        
        // set the 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        titleTextbox = new javax.swing.JTextField();
        assignmentTextbox = new javax.swing.JTextField();
        courseNameTextbox = new javax.swing.JTextField();
        titleLabel = new javax.swing.JLabel();
        formalTagPannel = new javax.swing.JPanel();
        formalDepartmentTemplateTextbox = new javax.swing.JTextField();
        formalTemplateTextbox = new javax.swing.JTextField();
        assignmentLabel = new javax.swing.JLabel();
        courseNumberTextbox = new javax.swing.JTextField();
        courseNumberCodeLabel = new javax.swing.JLabel();
        courseNameLabel = new javax.swing.JLabel();
        schoolTextbox = new javax.swing.JTextField();
        schoolLabel = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();
        labTeamMemberLabel = new javax.swing.JLabel();
        authorEditButton = new javax.swing.JButton();
        labTeamMemberEditButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        sectionsLabel = new javax.swing.JLabel();
        sectionsEditButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        sectionArea = new javax.swing.JTextArea();
        month1Combo = new javax.swing.JComboBox<>();
        day1Combo = new javax.swing.JComboBox<>();
        year1Combo = new javax.swing.JComboBox<>();
        experimentPerfomredOnLabel = new javax.swing.JLabel();
        month2combo = new javax.swing.JComboBox<>();
        day2combo = new javax.swing.JComboBox<>();
        year2Combo = new javax.swing.JComboBox<>();
        submissionDateLabel = new javax.swing.JLabel();
        generateButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        authorsTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        membersTextArea = new javax.swing.JTextArea();
        texButton = new javax.swing.JRadioButton();
        rtfButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Template Generator");
        setResizable(false);
        setSize(new java.awt.Dimension(700, 0));

        titleTextbox.setPreferredSize(new java.awt.Dimension(250, 20));

        assignmentTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignmentTextboxActionPerformed(evt);
            }
        });

        courseNameTextbox.setPreferredSize(new java.awt.Dimension(250, 20));
        courseNameTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseNameTextboxActionPerformed(evt);
            }
        });

        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleLabel.setText("Title:");
        titleLabel.setPreferredSize(new java.awt.Dimension(250, 14));

        formalTagPannel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        formalTagPannel.setPreferredSize(new java.awt.Dimension(270, 70));

        formalDepartmentTemplateTextbox.setEditable(false);
        formalDepartmentTemplateTextbox.setText(department);
        formalDepartmentTemplateTextbox.setPreferredSize(new java.awt.Dimension(250, 20));
        formalDepartmentTemplateTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formalDepartmentTemplateTextboxActionPerformed(evt);
            }
        });

        formalTemplateTextbox.setEditable(false);
        formalTemplateTextbox.setText("Formal");

        javax.swing.GroupLayout formalTagPannelLayout = new javax.swing.GroupLayout(formalTagPannel);
        formalTagPannel.setLayout(formalTagPannelLayout);
        formalTagPannelLayout.setHorizontalGroup(
            formalTagPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formalTagPannelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(formalTagPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formalDepartmentTemplateTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formalTemplateTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        formalTagPannelLayout.setVerticalGroup(
            formalTagPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formalTagPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formalDepartmentTemplateTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formalTemplateTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        assignmentLabel.setText("Assignment:");
        assignmentLabel.setPreferredSize(new java.awt.Dimension(250, 14));

        courseNumberCodeLabel.setText("Course Number Code:");
        courseNumberCodeLabel.setPreferredSize(new java.awt.Dimension(250, 14));

        courseNameLabel.setText("Course Name:");
        courseNameLabel.setPreferredSize(new java.awt.Dimension(250, 14));

        schoolTextbox.setPreferredSize(new java.awt.Dimension(250, 20));
        schoolTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolTextboxActionPerformed(evt);
            }
        });

        schoolLabel.setText("School:");
        schoolLabel.setPreferredSize(new java.awt.Dimension(250, 14));

        authorLabel.setText("Author(s):");

        labTeamMemberLabel.setText("Lab Team Members:");

        authorEditButton.setLabel("Edit");
        authorEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorEditButtonActionPerformed(evt);
            }
        });

        labTeamMemberEditButton.setLabel("Edit");
        labTeamMemberEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labTeamMemberEditButtonActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        sectionsLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sectionsLabel.setText("Sections");

        sectionsEditButton.setText("Edit");
        sectionsEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectionsEditButtonActionPerformed(evt);
            }
        });

        sectionArea.setEditable(false);
        sectionArea.setColumns(20);
        sectionArea.setRows(5);
        sectionArea.setText(h.getAll());
        jScrollPane2.setViewportView(sectionArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(sectionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sectionsEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(sectionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sectionsEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );

        month1Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January ", "Febuary ", "March ", "April ", "May ", "June ", "July ", "August ", "September ", "October", "November", "December" }));

        day1Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        day1Combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day1ComboActionPerformed(evt);
            }
        });

        year1Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040" }));
        year1Combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year1ComboActionPerformed(evt);
            }
        });

        experimentPerfomredOnLabel.setText("Experiment Performed on:");

        month2combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January ", "Febuary ", "March ", "April ", "May ", "June ", "July ", "August ", "September ", "October", "November", "December" }));

        day2combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        day2combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day2comboActionPerformed(evt);
            }
        });

        year2Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040" }));

        submissionDateLabel.setText("Submission Date:");

        generateButton.setText("Generate ");
        generateButton.setPreferredSize(new java.awt.Dimension(80, 20));
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        authorsTextArea.setEditable(false);
        authorsTextArea.setColumns(20);
        authorsTextArea.setRows(5);
        authorsTextArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                authorsTextAreaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(authorsTextArea);

        membersTextArea.setEditable(false);
        membersTextArea.setColumns(20);
        membersTextArea.setRows(5);
        jScrollPane3.setViewportView(membersTextArea);

        buttonGroup1.add(texButton);
        texButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        texButton.setSelected(true);
        texButton.setText(".tex");

        buttonGroup1.add(rtfButton);
        rtfButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rtfButton.setText(".rtf");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formalTagPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(assignmentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(titleTextbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(courseNumberTextbox)
                                .addComponent(assignmentTextbox)
                                .addComponent(courseNumberCodeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(courseNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(courseNameTextbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(schoolTextbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(schoolLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(authorLabel)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(authorEditButton)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(experimentPerfomredOnLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(month1Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(day1Combo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(submissionDateLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(month2combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(day2combo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(year2Combo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(year1Combo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(60, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(labTeamMemberEditButton)
                        .addGap(42, 42, 42)
                        .addComponent(generateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labTeamMemberLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(texButton)
                        .addGap(94, 94, 94))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(rtfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(134, 134, 134))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(formalTagPannel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(titleTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(assignmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(assignmentTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(courseNumberCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(courseNumberTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(courseNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(courseNameTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(experimentPerfomredOnLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(month1Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(day1Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(year1Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36))
                            .addComponent(submissionDateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(month2combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(day2combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(year2Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rtfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(generateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(schoolLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(schoolTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(authorLabel)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labTeamMemberLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(authorEditButton)
                                .addGap(57, 57, 57)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addComponent(labTeamMemberEditButton)
                                .addGap(62, 62, 62))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formalDepartmentTemplateTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formalDepartmentTemplateTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formalDepartmentTemplateTextboxActionPerformed

    private void assignmentTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignmentTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assignmentTextboxActionPerformed

    private void courseNameTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseNameTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseNameTextboxActionPerformed

    private void schoolTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schoolTextboxActionPerformed

    private void day1ComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day1ComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_day1ComboActionPerformed

    private void day2comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day2comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_day2comboActionPerformed

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        // write the sed commands
        script = new ScriptEditor();
        String ls = File.separator;
        String defaultDocName;
        if (format == FORMAT.RTF) {
            defaultDocName = "generatedDocument.rtf";
        } else {
            defaultDocName = "generatedDocument.rtf";
        }
        Path userDoc = Paths.get(defaultDocName);
        String memStr = "";
        String authStr = "";        
        String subDate = "";
        String expDate = "";

        
        subDate = day1Combo.getSelectedItem().toString() + " "
                  + month1Combo.getSelectedItem().toString() + " "
                  + year1Combo.getSelectedItem().toString();
        
        expDate = day2combo.getSelectedItem().toString() + " "
                  + month2combo.getSelectedItem().toString() + " "
                  + year2Combo.getSelectedItem().toString();        
        
        
        if (texButton.isSelected()) {
            format = FORMAT.TEX;
            if (members.isEmpty()) {
                memStr = " ";
            } else {
                memStr = "Lab Team: \\\n";
                for (int i = 0; i < members.size(); i++) {
                    memStr += members.get(i) + "\\\n";
                }
            }
            if (authors.isEmpty()) {
                authStr = " ";
            } else {
                for (int i = 0; i < authors.size(); i++) {
                    authStr += authors.get(i) + "\\\n";
                }   
            }
        }
        if (rtfButton.isSelected()) {
            format = FORMAT.RTF;
            if (members.isEmpty()) {
                memStr = " ";
            } else {
                memStr = "Lab Team: \\\\par ";
                for (int i = 0; i < members.size(); i++) {
                    memStr += members.get(i) + "\\\\par ";
                }
            }
            if (authors.isEmpty()) {
                authStr = " ";
            } else {
                for (int i = 0; i < authors.size(); i++) {
                    authStr += authors.get(i) + "\\\\par ";
                }       
            }
        }        

        Path userSaveLoc = null;
        final JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Save document...");
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal;


        returnVal = fc.showSaveDialog(this);
        userSaveLoc = fc.getSelectedFile().toPath();


        
        try {
            script.newCommand(ScriptEditor.TAG_TITLE, titleTextbox.getText());
            script.newCommand(ScriptEditor.TAG_ASSIGNMENT, assignmentTextbox.getText());
            script.newCommand(ScriptEditor.TAG_COURSE_CODE, courseNumberTextbox.getText());
            script.newCommand(ScriptEditor.TAG_COURSE_NAME, courseNameTextbox.getText());
            script.newCommand(ScriptEditor.TAG_DEPARTMENT, department);
            script.newCommand(ScriptEditor.TAG_SCHOOL, schoolTextbox.getText());
            script.newCommand(ScriptEditor.TAG_AUTHORS, authStr);
            script.newCommand(ScriptEditor.TAG_TEAM, memStr);
            script.newCommand(ScriptEditor.TAG_EXPERIMENT_DATE, expDate);
            script.newCommand(ScriptEditor.TAG_SUBMISSION_DATE, subDate);

            if (format == FORMAT.RTF) {
                script.newCommand(ScriptEditor.TAG_SECTIONS, h.formatRTF());
                script.newCommand(ScriptEditor.TAG_TOC, h.formatRTFToC());
                
            } else 
                script.newCommand(ScriptEditor.TAG_SECTIONS, h.formatTeX());

            try {
                // run commands
                if (format == FORMAT.TEX) {
                    defaultDocName = assignmentTextbox.getText() + ".tex";
                }
                else 
                    defaultDocName = assignmentTextbox.getText() + ".rtf";
                userDoc = script.runScript(template, format);
                
            } catch (InterruptedException ex) {
                
            }
            
            try {
                userSaveLoc = Paths.get(userSaveLoc.toString() + ls + defaultDocName);
                Files.deleteIfExists(userSaveLoc);
                Files.copy(userDoc, userSaveLoc, StandardCopyOption.COPY_ATTRIBUTES);
                JOptionPane.showMessageDialog(null, String.format("Successfully saved to: %s", 
                                                                  userSaveLoc.toString()));
                Files.delete(userDoc);
        } catch (FileAlreadyExistsException faeex) {

        }

        } catch (IOException ex) {
            
        }
    }//GEN-LAST:event_generateButtonActionPerformed

    private void year1ComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year1ComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_year1ComboActionPerformed

    private void authorEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorEditButtonActionPerformed
        NameEditor ne = new NameEditor(this, authors);
        ne.setVisible(true);
    }//GEN-LAST:event_authorEditButtonActionPerformed

    private void labTeamMemberEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labTeamMemberEditButtonActionPerformed
        NameEditor ne = new NameEditor(this, members);
        ne.setVisible(true);        
    }//GEN-LAST:event_labTeamMemberEditButtonActionPerformed

    private void authorsTextAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_authorsTextAreaMouseClicked
        // TODO add your handling code here:
        this.updateNamesAreas();
    }//GEN-LAST:event_authorsTextAreaMouseClicked

    private void sectionsEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectionsEditButtonActionPerformed
        SectionEditor se = new SectionEditor(this, h);
        se.setVisible(true);
    }//GEN-LAST:event_sectionsEditButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formal().setVisible(true);
            }
        });
    }
    
    public void updateNamesAreas() {
        String memStr = "";
        String authStr = "";
        
        for (int i = 0; i < members.size(); i++) {
            memStr += members.get(i) + "\n";
        }
        for (int i = 0; i < authors.size(); i++) {
            authStr += authors.get(i) + "\n";
        }
        
        authorsTextArea.setText(authStr);
        membersTextArea.setText(memStr);
    }
    
    public void updateSections() {
        sectionArea.setText(h.getAll());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel assignmentLabel;
    private javax.swing.JTextField assignmentTextbox;
    private javax.swing.JButton authorEditButton;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JTextArea authorsTextArea;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel courseNameLabel;
    private javax.swing.JTextField courseNameTextbox;
    private javax.swing.JLabel courseNumberCodeLabel;
    private javax.swing.JTextField courseNumberTextbox;
    private javax.swing.JComboBox<String> day1Combo;
    private javax.swing.JComboBox<String> day2combo;
    private javax.swing.JLabel experimentPerfomredOnLabel;
    private javax.swing.JTextField formalDepartmentTemplateTextbox;
    private javax.swing.JPanel formalTagPannel;
    private javax.swing.JTextField formalTemplateTextbox;
    private javax.swing.JButton generateButton;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton labTeamMemberEditButton;
    private javax.swing.JLabel labTeamMemberLabel;
    private javax.swing.JTextArea membersTextArea;
    private javax.swing.JComboBox<String> month1Combo;
    private javax.swing.JComboBox<String> month2combo;
    private javax.swing.JRadioButton rtfButton;
    private javax.swing.JLabel schoolLabel;
    private javax.swing.JTextField schoolTextbox;
    private javax.swing.JTextArea sectionArea;
    private javax.swing.JButton sectionsEditButton;
    private javax.swing.JLabel sectionsLabel;
    private javax.swing.JLabel submissionDateLabel;
    private javax.swing.JRadioButton texButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleTextbox;
    private javax.swing.JComboBox<String> year1Combo;
    private javax.swing.JComboBox<String> year2Combo;
    // End of variables declaration//GEN-END:variables
}
