/* File: Informal.java
 * Author: Chris Jacques, Malik Midani, Connor McGarty
 * Assignment: Template Generator - Team 5 Project EE333 Spring 2018
 * Vers: 1.0.0 04/20/18 
 * 
 */

import java.io.File;
import java.io.IOException;
import java.nio.file.FileAlreadyExistsException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;



/**
 * Graphical environment for editing informal report template.
 * 
 * @author Chris Jacques 
 */
public class Informal extends javax.swing.JDialog {
    
    private String department;
    private TEMPLATE template;
    private FORMAT   format;
    private Headings h;
    private ScriptEditor script;

    /**
     * Creates new form Informal
     *
     * @param parent frame gui was spawned from
     * @param modal lj
     */
    public Informal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /**
     * Constructs the informal frame. 
     * 
     * @param department department edited
     * @param template which template, formal or informal
     */
    public Informal(String department, TEMPLATE template) {
        h = new Headings(TEMPLATE.INFORMAL);
        this.template = template;
        this.department = department;
        
        initComponents(); 
        
        // set the 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        buttonGroup1 = new javax.swing.ButtonGroup();
        tagPanel = new javax.swing.JPanel();
        departmentTag = new javax.swing.JTextField();
        templateTag = new javax.swing.JTextField();
        toTextbox = new javax.swing.JTextField();
        toLabel = new javax.swing.JLabel();
        fromLabel = new javax.swing.JLabel();
        fromTextbox = new javax.swing.JTextField();
        monthLabel = new javax.swing.JLabel();
        monthCombo = new javax.swing.JComboBox<>();
        dayCombo = new javax.swing.JComboBox<>();
        dayLabel = new javax.swing.JLabel();
        yearCombo = new javax.swing.JComboBox<>();
        yearLabel = new javax.swing.JLabel();
        subjectTextbox = new javax.swing.JTextField();
        subjectLabel = new javax.swing.JLabel();
        headingsPanel = new javax.swing.JPanel();
        headingsLabel = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        sectionArea = new javax.swing.JTextArea();
        generateButton = new javax.swing.JButton();
        texButton = new javax.swing.JRadioButton();
        rtfButton = new javax.swing.JRadioButton();

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 355));

        tagPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tagPanel.setPreferredSize(new java.awt.Dimension(270, 70));

        departmentTag.setEditable(false);
        departmentTag.setText(department);
        departmentTag.setMinimumSize(new java.awt.Dimension(6, 25));
        departmentTag.setPreferredSize(new java.awt.Dimension(130, 25));
        departmentTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentTagActionPerformed(evt);
            }
        });

        templateTag.setEditable(false);
        templateTag.setText("Informal");
        templateTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                templateTagActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tagPanelLayout = new javax.swing.GroupLayout(tagPanel);
        tagPanel.setLayout(tagPanelLayout);
        tagPanelLayout.setHorizontalGroup(
            tagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tagPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(templateTag, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departmentTag, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        tagPanelLayout.setVerticalGroup(
            tagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tagPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(departmentTag, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(templateTag, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        departmentTag.getAccessibleContext().setAccessibleName("");

        toTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toTextboxActionPerformed(evt);
            }
        });

        toLabel.setText("To:");

        fromLabel.setText("From:");

        fromTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromTextboxActionPerformed(evt);
            }
        });

        monthLabel.setText("Month:");

        monthCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        monthCombo.setMinimumSize(new java.awt.Dimension(80, 20));
        monthCombo.setPreferredSize(new java.awt.Dimension(80, 20));

        dayCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dayCombo.setMinimumSize(new java.awt.Dimension(80, 20));
        dayCombo.setPreferredSize(new java.awt.Dimension(80, 20));

        dayLabel.setText("Day:");

        yearCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040" }));
        yearCombo.setMinimumSize(new java.awt.Dimension(80, 20));
        yearCombo.setPreferredSize(new java.awt.Dimension(80, 20));
        yearCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearComboActionPerformed(evt);
            }
        });

        yearLabel.setText("Year:");

        subjectTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectTextboxActionPerformed(evt);
            }
        });

        subjectLabel.setText("Subject:");

        headingsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        headingsLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        headingsLabel.setText("Headings:");

        editButton.setText("Edit");
        editButton.setPreferredSize(new java.awt.Dimension(80, 20));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        sectionArea.setEditable(false);
        sectionArea.setColumns(20);
        sectionArea.setRows(5);
        jScrollPane3.setViewportView(sectionArea);
        sectionArea.setText(h.getAll());

        javax.swing.GroupLayout headingsPanelLayout = new javax.swing.GroupLayout(headingsPanel);
        headingsPanel.setLayout(headingsPanelLayout);
        headingsPanelLayout.setHorizontalGroup(
            headingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headingsPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(headingsLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headingsPanelLayout.setVerticalGroup(
            headingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headingsLabel)
                .addGap(18, 18, 18)
                .addGroup(headingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(headingsPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11))
        );

        generateButton.setText("Generate");
        generateButton.setPreferredSize(new java.awt.Dimension(80, 20));
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(texButton);
        texButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        texButton.setSelected(true);
        texButton.setText(".tex");
        texButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(rtfButton);
        rtfButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rtfButton.setText(".rtf");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tagPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subjectTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(monthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(monthLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dayLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yearCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yearLabel)))
                            .addComponent(subjectLabel)
                            .addComponent(fromLabel)
                            .addComponent(toTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toLabel)
                            .addComponent(fromTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(texButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rtfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(headingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tagPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(toLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fromLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fromTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(monthLabel)
                            .addComponent(dayLabel)
                            .addComponent(yearLabel)))
                    .addComponent(headingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(monthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(yearCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rtfButton)
                        .addComponent(texButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(generateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(subjectLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subjectTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toTextboxActionPerformed

    private void fromTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromTextboxActionPerformed

    private void subjectTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectTextboxActionPerformed

    private void yearComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearComboActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        SectionEditor se = new SectionEditor(this, h);
        se.setVisible(true);
    }//GEN-LAST:event_editButtonActionPerformed

    /**
     * Grabs all information from user-editable fields, compiles them into a sed
     * script, and executes the script via ScriptEditor. Resulting file is copied
     * to user supplied path via a save dialogue.
     * 
     * @param evt 
     */
    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        // write the sed commands
        script = new ScriptEditor();
        String ls = File.separator;
        String defaultDocName;

        if (format == FORMAT.RTF) {
            defaultDocName = "generatedDocument.rtf";
        } else {
            defaultDocName = "generatedDocument.rtf";
        }
        Path userDoc = Paths.get(defaultDocName);
        String memStr = "";
        String authStr = "";        
        String date = "";


        date = dayCombo.getSelectedItem().toString() + " " + 
               monthCombo.getSelectedItem().toString() + " " +
               yearCombo.getSelectedItem().toString();
        
        if (texButton.isSelected()) {
            format = FORMAT.TEX;
        }
        else if (rtfButton.isSelected())
            format = FORMAT.RTF;

        
        Path userSaveLoc = null;
        final JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Save document...");
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal;


        returnVal = fc.showSaveDialog(this);
        userSaveLoc = fc.getSelectedFile().toPath();


        
        try {
            
            script.newCommand(ScriptEditor.TAG_MEMO_TO, toTextbox.getText());
            script.newCommand(ScriptEditor.TAG_MEMO_FROM, fromTextbox.getText());
            script.newCommand(ScriptEditor.TAG_MEMO_SUBJECT, subjectTextbox.getText());
            script.newCommand(ScriptEditor.TAG_MEMO_DATE, date);

            if (format == FORMAT.RTF) {
                script.newCommand(ScriptEditor.TAG_SECTIONS, h.formatRTF());
            } else 
                script.newCommand(ScriptEditor.TAG_SECTIONS, h.formatTeX());

            try {
                // run commands
                if (format == FORMAT.TEX) {
                    if (!subjectTextbox.getText().isEmpty())                    
                        defaultDocName = subjectTextbox.getText() + ".tex";
                    else {
                        defaultDocName = "myInformal.tex";
                    }
                }
                else {
                    if (!subjectTextbox.getText().isEmpty()) {
                        defaultDocName = subjectTextbox.getText() + ".rtf";
                    }
                    else {
                        defaultDocName = "myInformal.rtf";
                    }
                }
                userDoc = script.runScript(template, format);
                
            } catch (InterruptedException ex) {
                
            }
            
            try {
                userSaveLoc = Paths.get(userSaveLoc.toString() + ls + defaultDocName);
                Files.deleteIfExists(userSaveLoc);
                Files.copy(userDoc, userSaveLoc, StandardCopyOption.COPY_ATTRIBUTES);
                JOptionPane.showMessageDialog(null, String.format("Successfully saved to: %s", 
                                                                  userSaveLoc.toString()));
                Files.delete(userDoc);
        } catch (FileAlreadyExistsException faeex) {

        }

        } catch (IOException ex) {
            
        }        
        
    }//GEN-LAST:event_generateButtonActionPerformed

    private void templateTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_templateTagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_templateTagActionPerformed

    private void texButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texButtonActionPerformed

    private void departmentTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentTagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentTagActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Informal dialog = new Informal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    /**
     * Update the sections in the section text area. 
     */
    public void updateSections() {
        sectionArea.setText(h.getAll());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> dayCombo;
    private javax.swing.JLabel dayLabel;
    private javax.swing.JTextField departmentTag;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JTextField fromTextbox;
    private javax.swing.JButton generateButton;
    private javax.swing.JLabel headingsLabel;
    private javax.swing.JPanel headingsPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTree jTree1;
    private javax.swing.JComboBox<String> monthCombo;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JRadioButton rtfButton;
    private javax.swing.JTextArea sectionArea;
    private javax.swing.JLabel subjectLabel;
    private javax.swing.JTextField subjectTextbox;
    private javax.swing.JPanel tagPanel;
    private javax.swing.JTextField templateTag;
    private javax.swing.JRadioButton texButton;
    private javax.swing.JLabel toLabel;
    private javax.swing.JTextField toTextbox;
    private javax.swing.JComboBox<String> yearCombo;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
