/* File: StartScreen.java
 * Author: Collin Robinson, Chris Jacques
 * Assignment: Project 7 EE333 Spring 2018
 * Vers: 1.0.0 04/19/2018 
 * 
 */

/**
 * The main class of the Template Generator tool. Allows selection of formal or
 * informal template type, as well as the department. Will launch Formal or
 * Informal GUI based on user choice.
 * 
 * @author Collin Robinson
 */
public class StartScreen extends javax.swing.JFrame {

    /**
     * Creates new form StartScreen
     */
    public StartScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectFormatLabel = new javax.swing.JLabel();
        continueButton = new javax.swing.JButton();
        departmentSelection = new javax.swing.JComboBox<>();
        selectDepartmentLabel = new javax.swing.JLabel();
        formatSelection = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        selectFormatLabel.setText("Select Format");

        continueButton.setText("Continue ");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });
        continueButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                continueButtonKeyPressed(evt);
            }
        });

        departmentSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electrical Engineering (EE)", "Mechanical Engineering (ME)", "Civil Engineering (CE)", "Biomedical Engineering (BME)", "Material Science Engineering (MSE)" }));
        departmentSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentSelectionActionPerformed(evt);
            }
        });

        selectDepartmentLabel.setText("Select Department");

        formatSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Formal", "Informal" }));
        formatSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatSelectionActionPerformed(evt);
            }
        });

        jLabel1.setText("Created by Team 5: Connor McGarty, Collin Robinson, Malik Midani, Chris Jacques");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(formatSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(departmentSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addComponent(continueButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(186, 186, 186)
                                .addComponent(selectFormatLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addComponent(selectDepartmentLabel)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(selectDepartmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(departmentSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selectFormatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formatSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(continueButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Launches the next screen, either the Formal or Informal screen based on
     * user choice.
     * 
     * @param evt 
     */
    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed

        TEMPLATE template;
        Formal f;
        Informal inf;

        // store the department
        String department = departmentSelection.getSelectedItem().toString();

        // launch either formal or informal screen
        if (formatSelection.getSelectedIndex() == 0) {
            template = TEMPLATE.FORMAL;
            f = new Formal(department, template);
            f.setVisible(true);
        }
        else {
            template = TEMPLATE.INFORMAL;
            inf = new Informal(department, template);
            inf.setVisible(true);
        }
        
        this.dispose(); // close window without terminating program
        
    }//GEN-LAST:event_continueButtonActionPerformed

    /**
     * Saves the selected department and format on continue.
     * 
     * @param evt 
     */
    private void continueButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_continueButtonKeyPressed
        String department = (String) this.departmentSelection.getSelectedItem();
        String format = (String) this.formatSelection.getSelectedItem();

    }//GEN-LAST:event_continueButtonKeyPressed

    private void departmentSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentSelectionActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_departmentSelectionActionPerformed

    private void formatSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formatSelectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formatSelectionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continueButton;
    private javax.swing.JComboBox<String> departmentSelection;
    private javax.swing.JComboBox<String> formatSelection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel selectDepartmentLabel;
    private javax.swing.JLabel selectFormatLabel;
    // End of variables declaration//GEN-END:variables
}
